# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 18:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wifindbar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.PositiveSmallIntegerField()),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wifindbar.Bar')),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, unique=True)),
                ('obligatoria', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='calificacion',
            name='caracteristica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wifindbar.Caracteristica'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together=set([('user', 'bar', 'caracteristica')]),
        ),
        migrations.AlterIndexTogether(
            name='calificacion',
            index_together=set([('bar', 'caracteristica')]),
        ),
    ]
