# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifindbar', '0002_auto_20160908_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='latitud',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='bar',
            name='longitud',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
