# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 06:44
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifindbar', '0003_auto_20160908_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='bar',
            name='longitud',
        ),
        migrations.AddField(
            model_name='bar',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bar',
            name='coordenadas',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='bar',
            name='direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
